# Add custom settings here.
# please read https://pymumu.github.io/smartdns/config/basic-config/

server 223.5.5.5 -group bootstrapone -exclude-default-group
server 223.6.6.6 -group bootstrapone -exclude-default-group
nameserver /dns.alidns.com/bootstrapone

address /dns.alidns.com/#6
address /in-addr.arpa/#
address /ip6.arpa/#

serve-expired-ttl 345600
serve-expired-prefetch-time 43200
