# Add custom settings here.
# please read https://pymumu.github.io/smartdns/config/basic-config/

address /in-addr.arpa/#
address /ip6.arpa/#

serve-expired-ttl 345600
serve-expired-prefetch-time 43200
